version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '41000:80'

    php-fpm:
        build: ./
        working_dir: /application
        volumes:
            - '.:/application'
            - './php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
