version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '41000:80'

    php-fpm:
        build: ./
        working_dir: /application
        volumes:
            - '.:/application'
            - './php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASS: root
            MYSQL_DATABASE: teste

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: teste
